name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Project
        run: |
          npm ci
          npm run build

      - name: Sync Files
        run: |
          sudo rm -rf /var/www/maj/*

          sudo cp -r dist/* /var/www/maj/

          sudo cp -r /root/maj_website/public /var/www/maj/
          sudo cp /root/maj_website/robots.txt /var/www/maj/

          sudo chown -R www-data:www-data /var/www/maj
          sudo chmod -R 755 /var/www/maj